[project]
name = "eisback"
version = "1.0"
description = "Re-Wave the Eisbach"
requires-python = ">=3.12"
dependencies = [
    "taichi>=1.7.4",
    "jaxtyping>=0.3.3",
    "beartype>=0.22.6"
]